displayName=Fire Max Cape Removal
author=petty-mods
description=Hides players wearing fire max capes
tags=hide,players,fire max cape
version=1.00
plugins=com.firemaxcaperemoval.FireMaxCapeRemovalPlugin
build=standard