displayName=Fire Max Cape Removal
author=petty-mods
description=Replaces fire max capes with regular fire capes.
tags=replace,players,fire max cape
version=1.00
plugins=com.firemaxcaperemoval.FireMaxCapeRemovalPlugin
build=standard